language: r
cache: packages
sudo: false
dist: trusty
env: R_CODECOV=true
notifications:
  email:
    on_success: change
    on_failure: change
after_success:
  - if [[ "${R_CODECOV}" ]]; then R -e 'covr::codecov()'; fi
